In [1]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
b=np.zeros((3,3))
print(b)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
c=np.full((3,3),5)
print(c)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [6]:
d=np.random.random((3,3))
print("\n A random array:\n ",d)



 A random array:
  [[0.40867397 0.3026199  0.45870351]
 [0.18353755 0.53521912 0.64558704]
 [0.71904811 0.56151876 0.1192035 ]]


In [7]:
e=np.arange(0,30,2)
print(e)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]


In [8]:
arr=np.array([[1,2,3,4],[5,6,9,8],[1,2,0,1]])
print(arr)


[[1 2 3 4]
 [5 6 9 8]
 [1 2 0 1]]


In [13]:
newarr=arr.reshape(4,3)
print(newarr)


[[1 2 3]
 [4 5 6]
 [9 8 1]
 [2 0 1]]


In [14]:
print("\n size of the array :",arr.size)



 size of the array : 12


In [16]:
flat=arr.flatten()
print(flat)

[1 2 3 4 5 6 9 8 1 2 0 1]


In [29]:
tem=np.array([[1,2,3,4],[4,5,6,7]])
tem2=np.array([[3,7,8,9],[4,1,2,7]])
join=np.concatenate((tem,tem2))
print(join)


[[1 2 3 4]
 [4 5 6 7]
 [3 7 8 9]
 [4 1 2 7]]


In [31]:
arr=np.hstack((tem,tem2))
print(arr)

[[1 2 3 4 3 7 8 9]
 [4 5 6 7 4 1 2 7]]


In [32]:
arr=np.vstack((tem,tem2))
print(arr)


[[1 2 3 4]
 [4 5 6 7]
 [3 7 8 9]
 [4 1 2 7]]


In [35]:
arr=np.dstack((tem,tem2))
print(arr)

[[[1 3]
  [2 7]
  [3 8]
  [4 9]]

 [[4 4]
  [5 1]
  [6 2]
  [7 7]]]


In [38]:
arr=np.array([1,2,3,4,5])
newarr=np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5])]


In [39]:
arr=np.array([1,2,3,4,5,4,4])
print("original array:",arr)
x=np.where(arr==4)
print("\n indexes where the value is 4 :",x)


original array: [1 2 3 4 5 4 4]

 indexes where the value is 4 : (array([3, 5, 6], dtype=int64),)


In [42]:
ar1=np.array([4,2,7,9,3,2,1])
ar1=np.where(arr%2==0)
print("original array :",arr)
print("\n indexes where the values are even :",ar1)


original array : (array([0, 1, 5], dtype=int64),)

 indexes where the values are even : (array([3, 5, 6], dtype=int64),)


In [ ]:
#20/7/2024
#to perform numpy functions  


In [2]:
import numpy as np
arr=np.array([
              [-1,2,0,4],
              [4,-0.5,6,0],
              [2.6,0,7,8],
              [3,-7,4,2.0]
             ])
print("ordinary array :\n",arr)
print("\n Every other rows :[0:3:2]:\n",arr[0:3:2])


ordinary array :
 [[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]

 Every other rows :[0:3:2]:
 [[-1.   2.   0.   4. ]
 [ 2.6  0.   7.   8. ]]


In [4]:
#integer array indexing example 
temp=arr[[0,1,2,3],[3,2,1,0]]
print("\n Elements at indices (0,3),(1,2),(2,1),(3,0):",temp)



 Elements at indices (0,3),(1,2),(2,1),(3,0): [4. 6. 0. 3.]


In [5]:
#boolean array indexing example 
cond =arr>2
#cond is boolean array 
temp=arr[cond]
print("\n Elements graeter then  2:\n",temp)



 Elements graeter then  2:
 [4.  4.  6.  2.6 7.  8.  3.  4. ]


In [8]:
#return every other element form the entire array :
arr=np.array([1,2,3,4,5,6,7])
print("\n Original array :",arr)
print("\n Returns every other elements in the array[::2]:",arr[::2])



 Original array : [1 2 3 4 5 6 7]

 Returns every other elements in the array[::2]: [1 3 5 7]


In [9]:
#joining two array 
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)


[1 2 3 4 5 6]


In [13]:
#Horizontal join 
arr=np.hstack((arr1,arr2))
print(arr)


[1 2 3 4 5 6]


In [12]:
#vertical join 
arr=np.vstack((arr1,arr2))
print("Vertical joining :\n",arr)


Vertical joining :
 [[1 2 3]
 [4 5 6]]


In [14]:
#Depth join 
arr=np.dstack((arr1,arr2))
print("\n Depth joining :\n",arr)



 Depth joining :
 [[[1 4]
  [2 5]
  [3 6]]]


In [17]:
#Splitting array 
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print("\n Original array :\n",arr)
print("splitted array    :\n",newarr)
#displaying splitted array in another form 
print(newarr[0])
print(newarr[1])
print(newarr[2])




 Original array :
 [1 2 3 4 5 6]
splitted array    :
 [array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]


In [ ]:
# EXPERIMENT 3 Numpy -3 To perform numpy operations 

In [23]:
import numpy as np
#indexes where the value of four is :
arr=np.array([1,2,3,4,5,4,4,5])
print("original array:",arr)
x=np.where(arr==5)
print(x)


original array: [1 2 3 4 5 4 4 5]
(array([4, 7], dtype=int64),)


In [24]:
# indexes where the values are even :
arr=np.array([1,2,3,4,5,6,7,8])
x=np.where(arr%2==0)
print("\n the Original array \n",arr)
print("\n the index where the values are even :",x)



 the Original array 
 [1 2 3 4 5 6 7 8]

 the index where the values are even : (array([1, 3, 5, 7], dtype=int64),)


In [27]:
#indexes where the values 3 should be inserted , stsrting from right 
x=np.searchsorted(arr,3,side='left')
print("\nidexes where the value 3 should be inserted, starting from the right :",x)



idexes where the value 3 should be inserted, starting from the right : 2


In [29]:
#Sorting the array 
arr=np.array([3,2,0,1])
print("\n original array :",arr)
print("\n Sorted array:",np.sort(arr))

arr=np.array([[3,2,1],[5,0,1]])
print("\n Original array:",arr)
print("\n Sorted array  :",np.sort(arr))



 original array : [3 2 0 1]

 Sorted array: [0 1 2 3]

 Original array: [[3 2 1]
 [5 0 1]]

 Sorted array  : [[1 2 3]
 [0 1 5]]


In [40]:
#filter 
arr=np.array([41,42,43,44])
x=[True, False, True, False]
newarr=arr[x]
print("\n filter index :",x)
print("\n filter array :",newarr)

arr=np.array([41,42,43,44])
fil_arr=arr>42
newarr=arr[fil_arr]
print("\n Filter array : condition -> 42:",fil_arr)
print("\n New array    :",newarr)





 filter index : [True, False, True, False]

 filter array : [41 43]

 Filter array : condition -> 42: [False False  True  True]

 New array    : [43 44]


In [3]:
import numpy as np
arr1=[10,20,30,40,50]
arr2=[2,4,5,8,9]
a=np.array(arr1)
b=np.array(arr2)
print("vector addition")
print(a+b)
print("\n vector difference")
print(a-b)
print("\n vector multiplication")
print(a*b)
print("\n vector division")
print(a/b)
print("\n vector dot product")
print(a.dot(b))
print("\n scalar multiplication")
s=5
print("result",a*s)


vector addition
[12 24 35 48 59]

 vector difference
[ 8 16 25 32 41]

 vector multiplication
[ 20  80 150 320 450]

 vector division
[5.         5.         6.         5.         5.55555556]

 vector dot product
1020

 scalar multiplication
result [ 50 100 150 200 250]
